const SLIDES_QUANTITY = 4;
const SLIDE_TIME = 3000;

const REGEXPS = {
    name: {
        "en" : "^[A-Z][a-z]{1,30}(\\-?[A-Z][a-z]{1,30})?$",
        "gr": "^[A-Ω][α-ωόάέίώύή]{1,30}(\\-?[A-Ω][α-ω]{1,30})?$"
    },
    checkin: "^([0-9]{2}\\/){2}[0-9]{4}$",
    checkout: "^([0-9]{2}\\/){2}[0-9]{4}$",
    email: "^[a-z0-9\\-_\\.]{1,255}@[a-z0-9\\-]{1,64}(\\.[a-z\\-]{2,20}){1,2}$",
    phone: "^[0-9\\+]{1,}[0-9\\- ]{3,15}$",
    country: {
        "en" : "^[A-Za-z \\.\\(\\)]{1,80}$",
        "gr" : "^[A-Ω][α-ωόάέίώύή]{1,80}$"
    }
};

const MESSAGES = {
    "send-ok" : {
        "en" : "Your reservation has been successfully sent",
        "gr" : "Η κράτηση σάς έχει αποσταλεί επιτυχώς"
    },
    "send-error" : {
        "en" : "Fill in all the textfields correctly",
        "gr" : "Συμπλήρωσε όλα τα πεδία σωστά"
    }
};

const time = new Clock("#clock1");

changeMenu("#navbar");

const availableTags = {
en : 
[
        "Afghanistan",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas (the)",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia (Plurinational State of)",
        "Bonaire",
        "Sint Eustatius and Saba",
        "Bosnia and Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory (the)",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cayman Islands (the)",
        "Central African Republic (the)",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands (the)",
        "Colombia",
        "Comoros (the)",
        "Congo (the Democratic Republic of the)",
        "Congo (the)",
        "Cook Islands (the)",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Curaçao",
        "Cyprus",
        "Czechia",
        "Côte d'Ivoire",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic (the)",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Falkland Islands (the) [Malvinas]",
        "Faroe Islands (the)",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories (the)",
        "Gabon",
        "Gambia (the)",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard Island and McDonald Islands",
        "Holy See (the)",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran (Islamic Republic of)",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jersey",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea (the Democratic People's Republic of)",
        "Korea (the Republic of)",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic (the)",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands (the)",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia (Federated States of)",
        "Moldova (the Republic of)",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands (the)",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger (the)",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands (the)",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine",
        "State of",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines (the)",
        "Pitcairn",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Republic of North Macedonia",
        "Romania",
        "Russian Federation (the)",
        "Rwanda",
        "Réunion",
        "Saint Barthélemy",
        "Saint Helena",
        "Ascension and Tristan da Cunha",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin (French part)",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Sint Maarten (Dutch part)",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan (the)",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "United Republic of",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands (the)",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates (the)",
        "United Kingdom of Great Britain and Northern Ireland (the)",
        "United States Minor Outlying Islands (the)",
        "United States of America (the)",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela (Bolivarian Republic of)",
        "Viet Nam",
        "Virgin Islands (British)",
        "Virgin Islands (U.S.)",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe",
        "Åland Islands"
    ],
    gr : [
        "Αβησσυνία",
"Αγγλία",
"Αγκόλα",
"Αίγυπτος",
"Αιθιοπία",
"Ακτή Ελεφαντοστού",
"Αλβανία",
"Αλγερία",
"Ανατολικό Τιμόρ",
"Ανδόρα",
"Αούστρια",
"Αργεντινή",
"Αρμενία",
"Αυστραλία",
"Αυστρία",
"Αφγανιστάν",
"Βανουάτου",
"Βέλγιο",
"Βενεζουέλα",
"Βιετνάμ",
"Βιρμανία",
"Βολιβία",
"Βόρεια Κορέα",
"Βοσνία",
"Βοσνία Ερζεγοβίνη",
"Βοσνία και Ερζεγοβίνη",
"Βουλγαρία",
"Βραζιλία",
"Γαλλία",
"Γερμανία",
"Γκάμπια",
"Γκαμπόν",
"Γουατεμάλα",
"Γουιάνα",
"Γουινέα Μπισσάου",
"Γρενάδα",
"Γροιλανδία",
"Δανία",
"Δομινίκα",
"Δομινικανή Δημοκρατία",
"Ελβετία",
"Ελλάδα",
"Ελ Σαλβαδόρ",
"Ερυθραία",
"Εσθονία",
"Ηνωμένα Αραβικά Εμιράτα",
"Ηνωμένο Βασίλειο",
"ΗΠΑ",
"Ιαπωνία",
"Ινδία",
"Ινδονησία",
"Ιορδανία",
"Ιράκ",
"Ιράν",
"Ιρλανδία",
"Ισημερινός",
"Ισλανδία",
"Ισπανία",
"Ισραήλ",
"Ιταλία",
"Καζακστάν",
"Καμπότζη",
"Καναδάς",
"Κατάρ",
"Κάτω Χώρες",
"Κένυα",
"Κίνα",
"Κιργιζία",
"Κιριμπάτι",
"Κολομβία",
"Κομόρες",
"Κορέα",
"Κόστα Ρίκα",
"Κούβα",
"Κουβέιτ",
"Κράτος της Παλαιστίνης",
"Κροατία",
"Κύπρος",
"Λάος",
"Λετονία",
"Λευκορωσία",
"Λεχία",
"Λίβανος",
"Λιβερία",
"Λιθουανία",
"Λουξεμβούργο",
"Μαδαγασκάρη",
"Μαλαισία",
"Μαλάουι",
"Μαλδίβες",
"Μάλι",
"Μάλτα",
"Μαρόκο",
"Μαυριτανία",
"Μαυροβούνιο",
"Μεξικό",
"Μιανμάρ",
"Μικρονησία",
"Μογγολία",
"Μοζαμβίκη",
"Μολδαβία",
"Μπαγκλαντές",
"Μπαρμπάντος",
"Μπαχάμες",
"Μπαχρέιν",
"Μπελίζ",
"Μπενίν",
"Μποτσουάνα",
"Μπούρμα",
"Μπουτάν",
"Μπρουνέι",
"Ναμίμπια",
"Ναούρου",
"Νέα Ζηλανδία",
"Νεπάλ",
"Νησιά του Σολομώντα",
"Νήσοι Μάρσαλ",
"Νήσοι Σολομώντα",
"Νίγηρας",
"Νιγηρία",
"Νικαράγουα",
"Νιούε",
"Νορβηγία",
"Νότια Αφρική",
"Νότια Κορέα",
"Ντουμπάι",
"Ολλανδία",
"Ομάν",
"Ονδούρα",
"Ουαλία",
"Ουγγαρία",
"Ουζμπεκιστάν",
"Ουκρανία",
"Ουρουγουάη",
"Πακιστάν",
"Παλάου",
"Παναμάς",
"Παπούα Νέα Γουινέα",
"Παραγουάη",
"Περού",
"Περσία",
"Πολωνία",
"Πορτογαλία",
"Πουέρτο Ρίκο",
"Πράσινο Ακρωτήριο",
"Ρουάντα",
"Ρουμανία",
"Ρωσία",
"Ρωσική Ομοσπονδία",
"Σαμόα",
"Σαουδική Αραβία",
"Σερβία",
"Σιγκαπούρη",
"Σιέρα Λεόνε",
"Σκωτία",
"Σλοβακία",
"Σλοβενία",
"Σομαλία",
"Σουαζιλάνδη",
"Σουδάν",
"Σουηδία",
"Σουρινάμ",
"Σρι Λάνκα",
"Συρία",
"Τανζανία",
"Τατζικιστάν",
"Τζαμάικα",
"Τόγκο",
"Τόνγκα",
"Τουβαλού",
"Τουρκία",
"Τρινιντάντ και Τομπάγκο",
"Τσεχία",
"Τυνησία",
"Υεμένη",
"Φιλιππίνες",
"Φινλανδία",
"Φίτζι",
"Χιλή"
    ]
};



